-- Q1. What is the total revenue generated by male vs. female customers?

Select gender , SUM(purchase_amount) as Revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id,purchase_amount 
FROM customer
WHERE discount_applied = 'YES' and purchase_amount >= (SELECT AVG(purchase_amount)from customer);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating)) AS 'AVERAGE_RATING'
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type , ROUND(AVG(purchase_amount)) AS 'Avg_Purchase_Amount'
FROM customer
where shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS Avg_Spend,
ROUND(SUM(purchase_amount)) AS Total_Spend
FROM customer
GROUP BY subscription_status
ORDER BY total_spend desc ,avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
ROUND(100* SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END )/COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

-- USING WITH STATEMENT
WITH  customer_type AS(
SELECT customer_id,previous_purchases,
CASE 
	WHEN previous_purchases=1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    WHEN previous_purchases>=10 THEN 'Loyal'
    END AS customer_segment
FROM customer
)
SELECT customer_segment,COUNT(*) AS 'Number of Customers'
from customer_type
GROUP BY customer_segment
ORDER BY 'Number of Customers' desc;

-- SELECT 
-- 	CASE 
-- 		WHEN previous_purchases=1 THEN 'New'
-- 		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
-- 		WHEN previous_purchases>=10 THEN 'Loyal'
-- 	END AS customer_segment,
-- 	COUNT(*) AS Total_Customers
-- FROM customer
-- GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
	SELECT category,item_purchased,
	COUNT(customer_id) AS total_orders
	FROM customer
	GROUP BY category, item_purchased
),

ranked_items AS (
SELECT category,item_purchased,total_orders,
	ROW_NUMBER() OVER(
            PARTITION BY category
            ORDER BY total_orders DESC
        ) AS item_rank
FROM item_counts
)

SELECT item_rank,category,item_purchased,total_orders
FROM ranked_items
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases>5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount)as Total_revenue
FROM customer
GROUP BY age_group
ORDER BY Total_revenue desc